/* Stub for tinfl test compilation: miniz_export.h is normally generated by
 * miniz's CMake build. When compiling tinfl sources directly, all exports
 * are static-only so MINIZ_EXPORT can be empty. */
#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H
#define MINIZ_EXPORT
#define MINIZ_NO_EXPORT
#endif
