#!/bin/sh

# this usage of the 'indent' program should format code to the specifications
# listed here: http://developer.pidgin.im/wiki/CodingStandards 
indent -bap -bbb -bbo -blf -bls -br -ce -i8 -l80 -lp -npcs -nprs -psl -saf \
-sai -saw -ts8 $*

